### ISSUE TITLE
Erro ao instalar o plugin no apache 2.2 com php 7.2 com wordpress 5.2.2 com o tema bvs2012

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#61]
Fatal error: Uncaught Error: Call to undefined function pll_default_language() in /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-content/plugins/bibliographic/template-functions.php:88 Stack trace: #0 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-content/plugins/bibliographic/template/home.php(83): real_site_url('biblio') #1 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-content/plugins/bibliographic/bibliographic.php(134): include('/home/apps/epor...') #2 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-includes/class-wp-hook.php(286): Bibliographic_Plugin->template_redirect('') #3 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-includes/template-loader.php(13): do_action('template_redire...') #6 /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-blog-header.php(19): req in /home/apps/eportuguese.org/wp-eportuguese/htdocs/wp-content/plugins/bibliographic/template-functions.php on line 88
O site está passando por dificuldades técnicas.

**Comment by marcoslmori** [comment]
tem que ativar o polylang e definir pelo menos um idioma
